name: obs-node

on:
  workflow_dispatch:

env:
  GITHUB_USER: Mengli619
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Build with srt support: https://gist.github.com/Kusmeroglu/ef81c4f96369f890fcdc0616652430ad
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: registry.cn-beijing.aliyuncs.com/mengli/obs-node-linux-workflow-container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: bash scripts/build.sh all

      - name: Upload
        run: npm run upload
        shell: bash
