name: obs-node

on:
  push:
    tags:
      - '*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: bash scripts/build.sh all
        shell: bash

      - name: Upload
        run: npm run upload
        shell: bash

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: bash scripts/build.sh all
        shell: bash

      - name: Upload
        run: npm run upload
        shell: bash
